### ISSUE TITLE
Ubuntu 14.04 Segment Fault when running basic.py

### ISSUE THREAD

**Issue by xjwxjw** [Farama-Foundation/ViZDoom#143]
I got segment fault when run basic.py.
The system configuration:
Ubuntu 14.04
Memory: 125.8GiB
Processor: Intel Xeon(R) CPU E5-2690 v3@2.60Hz * 16
Os type:64-bit
Display Card:GTX 980Ti
I notice that the seg-fault occurs at vizdoom::fileExists(std::string), and I have no file named "_vizdoom.cfg".
[GDB_BackTrace.txt](https://github.com/Marqt/ViZDoom/files/616314/GDB_BackTrace.txt)

**Comment by ebonyclock** [comment]
_vizdoom.cfg is optional so it should not matter.

What version of vizdoom and what version of repo code do you have? We have updated lots of things connected to paths and made vizdoom pip installable but #101 is still there so it might be this.

**Comment by xjwxjw** [comment]
The version of vizdoom is 1.1.0rc1. When building the source code, the system could not find boost_iostreams, so I add set(BOOST_LIBRARYDIR /usr/lib/x86_64-linux-gnu/) in CamkeLists.txt. It still shows that :"Could NOT find GME (missing:  GME_INCLUDE_DIR)" and "Could not find FMOD include files",but it seems the makefile could be generated.I do not set any paths like #101, just simply type python basic.py in the terminal, and it get the segmentation fault.

**Comment by ebonyclock** [comment]
It should work without GME and FMOD. Could you show the output of cmake?

**Comment by xjwxjw** [comment]
Here is the cmake output file.
[CMAKE.txt](https://github.com/Marqt/ViZDoom/files/618652/CMAKE.txt)
May be there is something wrong with the Timidity++. Because after I installed the Timidity++, the ubuntu crashed, then I have to turn it off in the boot sequence.Is there any way to test whether the Timidity++ module works normally?Or is there any options that can run the basic.py getting rid of Timidity++?

**Comment by ebonyclock** [comment]
Please first clean Cmakes cache and then repeat (e.g. ./cmake_clean.sh). Do you use boost installed from sources?

**Comment by xjwxjw** [comment]
I forget how I install the boost, is there any way to check it?
[cmake.txt](https://github.com/Marqt/ViZDoom/files/618922/cmake.txt)

**Comment by xjwxjw** [comment]
I search the file which related to libboost and get this: 
[libboost.txt](https://github.com/Marqt/ViZDoom/files/618953/libboost.txt)
It seems that not all the libboost libraries version are 1.61.0 and the FFMpeg package also contains  libboost_1_61_0. So may be I do not ever install boost and only install the libboost-all-dev.

**Comment by ebonyclock** [comment]
It looks like finds boost correctly but python versions seems to be messedup. Some parts are from anaconda and some are from the default system python.

NUMPY_ROOT_DIR    = /usr/local' 
vs 
NUMPY_INCLUDES    = /home/xu-jinwgei/anaconda2/lib/python2.7/site-packages/numpy/core/include

It might be this.

**Comment by xjwxjw** [comment]
So do you mean I should set the NUMPY_INCLUDES to the "/home/xu-jinwgei/anaconda2/lib/python2.7/site-packages/numpy/core/include"?

**Comment by ebonyclock** [comment]
Yes, it would be nice if you tried, at least we'll  know something. It's not a nice solution in long term but maybe wil work for now.

**Comment by xjwxjw** [comment]
I try to set NUMPY_ROOT_DIR:/home/xu-jinwgei/anaconda2/lib/python2.7/site-packages/numpy/, but still failed. And the gdb report that the segmentation fault always occurs at vizdoom::fileExists(std::string) ().

**Comment by mwydmuch** [comment]
Closing an old issue, NumPy support was rewritten, and Python 2.7 is no longer supported.
