### ISSUE TITLE
"Perfect" configured built-in bot behaves silly?

### ISSUE THREAD

**Issue by pengsun** [Farama-Foundation/ViZDoom#174]
Hi, 

I drew a small map in rectangle and added built-in bots following the cig_bots.py/cig.wad/cig.cfg example. However, I observed that the bot behaves strange: it keeps walking all the way to the wall and got stuck there. I had set the bots.cfg to make it a strong bot:
{
    name        d1
    aiming      100
    perfection  100
    reaction    100
    isp         100
    color       "50 50 60"
    skin        base
    //weaponpref    012345678
}
and added the bot using the code below:
```Python
game.send_game_command("addbot d1")
```
 
Any clue for this? Hope you could help :-)

**Comment by ebonyclock** [comment]
Yes, they tend to behave silly but I am afraid that we can't do anything about this.

**Comment by pengsun** [comment]
Okay, thanks for your response! Just worried if I made something wrong...

By the way, a related question: when I trained the agent to fight with built-in monsters, I found there seemed something wrong with the ACS speed setting code:
```
SetActorProperty(target_id, APROP_Speed,  speed);
``` 
Once it is called (and compiled), the monster just stands still, no moving at all, in regards of the value `speed`. But the monster does walk around when commenting out the code. Is it expected behavior?

**Comment by pengsun** [comment]
Hi,
Why the bots here look "smarter"? At least they don't walk into corner and get stuck there?
https://www.youtube.com/watch?v=nakohvx-k5U&index=2&list=PLduGZax9wmiHg-XPFSgqGg8PEAV51q1FT

BTW, why the scene/player/item appearance of cig 2016 (which looks like this: https://www.youtube.com/watch?v=Qv4esGWOg7w&list=PLafjlWAtoqjPAP-cNcehGGg-Wzge-zn1J) is different from the cig.wad shipped with vizdoom project (which looks like this: https://www.youtube.com/watch?v=PY0WsAzZZYI)?

**Comment by ebonyclock** [comment]
I think that they changed the map and put monsters skinned like players to simulate bots that is way they behave like they do.

As for the appearance we used doom2.wad for recordings because it looks better, it's not a matter of cig.wad. Unless you are referring to maps that aren't in cig.wad, they have been added in cig_with_unknown.wad

**Comment by pengsun** [comment]
Hi @ebonyclock, thanks so much for your quick response! 

* The bots
Could you give some hints on how to spawn various marine-like monsters? Previously I tried this, but:
1) The RocketMarine monster is always in white, how to change its color?
2) I can't find a reliable way to maintain a fixed maximum number of monsters (I tried simple reference counter in ACS script but it doesn't work due to unknown reason. Shall we have to do the spawning periodically like in "death_match.wad"?)

* The appearance
Yes I was talking about cig with known map. Does it mean it is fine to train our submission with freedoom.wad and we should not worry about a different appearance during the real match?

**Comment by mwydmuch** [comment]
Old issue, closing.
