### ISSUE TITLE
"map-auto-change" bug is still there?

### ISSUE THREAD

**Issue by pengsun** [Farama-Foundation/ViZDoom#177]
Hi,

This one #166 seems still there in the latest commit?

In the `cig_bots.py` example, I used another wad by chaning this line
https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/cig_bots.py#L11
to 
`game.load_config("../../scenarios/multi.cfg")`
and setting number of bots to 2, then I found the map changed after each episode.

**Comment by mwydmuch** [comment]
Forgive a long response time on this one.
I see a reason for that: `<bot name> exited the level.`. Well, it definitely shouldn't happen and we should probably add support for this situation, but there also should be no exit on multiplayer map.
You can add `+sv_noexit 1` to `game.add_game_args` to prevent this and then everything will work nicely.

**Comment by mwydmuch** [comment]
This is an edge case, I don't think it requires fixing. Closing.
