### ISSUE TITLE
Regression: getState will now return nullptr/null/None if game is in the terminal state.

### ISSUE THREAD

**Issue by hholst80** [Farama-Foundation/ViZDoom#183]
We need terminal states.

**Comment by wjaskowski** [comment]
Why do you need them?


--
Wojciech Jaśkowski, Ph.D.
Laboratory of Intelligent Decision Support Systems
Institute of Computing Science
Poznan University of Technology, Poland
http://www.cs.put.poznan.pl/wjaskowski

**Comment by hholst80** [comment]
Our codes assumes there is a terminal state, cf. OpenAI gym environments and their Universe framework.

**Comment by wjaskowski** [comment]
But you can add a simple condition on that, don't you? The problem is there
is physically no data on the terminal state in Doom.

**Comment by hholst80** [comment]
> But you can add a simple condition on that, don't you? 

We could return a zeros array or something like that but we require an observation - even if it is a dummy observation.

As I remember (in the few instances I did die in Doom, ;-)) the camera was still active even after dying. We should be able to capture a frame even when the player health is zero? This must be a limitation in ViZDoom rather than in the underlying ZDoom engine.

**Comment by mwydmuch** [comment]
At this point, 100% it won't be changed in the original API, closing.
