### ISSUE TITLE
building process hang on OS X

### ISSUE THREAD

**Issue by CaoZhongZ** [Farama-Foundation/ViZDoom#198]
cd /Users/caozhong/Workspace/zdoom/ViZDoom/build/src/vizdoom/wadsrc && /usr/local/Cellar/cmake/3.8.0/bin/cmake -E touch /Users/caozhong/Workspace/zdoom/ViZDoom/build/src/vizdoom/tools/zipdir/zipdir

It takes quite long at this command. Anything wrong?

**Comment by mwydmuch** [comment]
Old issue, closing.
