### ISSUE TITLE
FMOD

### ISSUE THREAD

**Issue by PDLBDeveloper** [Farama-Foundation/ViZDoom#226]
Hi! 

I would love to use vizdoom for my Deep Learning experiments. I am working on MacOS using virtualenv for Python.

Unfortunately "pip install vizdoom" does not work. It seem so be related to FMOD EX which I have installed to "/Developer/FMOD Programmers API Mac". This error shows up:

> CMake Error at src/vizdoom/src/CMakeLists.txt:856 (add_executable):
>       Cannot find source file:
> 
>         FMOD_LIBRARY-NOTFOUND

Any ideas?

**Comment by mwydmuch** [comment]
As work around you can clone repository and modify setup.py to add "-DNO_FMOD=ON" argument to CMake command. Then install with pip (`cd ViZDoom && pip install .`).

**Comment by mwydmuch** [comment]
This is fixed if I remember correctly. Closing.
