### ISSUE TITLE
NameError: name 'DoomGame' is not defined arouse in windows 10 os

### ISSUE THREAD

**Issue by SystemErrorWang** [Farama-Foundation/ViZDoom#240]
Dear vizdoom team:

I am installing vizdoom and testing RL code on my laptop (windows10 os, python3.6 on anaconda3), and although the vizdoom seems to be successfully installed, I came across the following problem:
**Traceback (most recent call last):

  File "<ipython-input-4-99f84f351e0b>", line 1, in <module>
    runfile('C:/Users/System_Error/Documents/DLmodels/DeepRL-Agents-master/A3C.py', wdir='C:/Users/System_Error/Documents/DLmodels/DeepRL-Agents-master')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/System_Error/Documents/DLmodels/DeepRL-Agents-master/A3C.py", line 325, in <module>
    workers.append(Worker(DoomGame(),i,s_size,a_size,trainer,model_path,global_episodes))

NameError: name 'DoomGame' is not defined

**

If you have any idea of this, would you please give me some help? Also, a pip install package for windows in highly appreciated. Thank you a lot!

**Comment by mwydmuch** [comment]
Hello @SystemErrorWang,
sorry for long response time. 

How exactly did you install ViZDoom on Windows?
And did you simply try to launch basic.py example?

**Comment by guuswinkelmolen** [comment]
Hey @mwydmuch 
I am experiencing a very similar problem when running the basic.py test code. I tried putting the vizdoom folder in both the general anaconda3 site-packages and my environment specific site-packages folder, but without any success. Python allows me to import vizdoom without a problem but then throws the following error: (running the basic.py demo)
` File "basic.py", line 22, in <module>
    game = vzd.DoomGame()
AttributeError: module 'vizdoom' has no attribute 'DoomGame'`
I have researched different threats on the internet but can't seem to find a solution for this problem in any of those.

**Comment by juliux** [comment]
We had the same problem, and basically looks like was an issue installing with pip. After follow up a virtual environtment and the next procedure it was ok.

Install Vizdoom

Follow these instructions to install the Vizdoom build dependencies

# ZDoom dependencies
sudo apt-get install build-essential zlib1g-dev libsdl2-dev libjpeg-dev \
nasm tar libbz2-dev libgtk2.0-dev cmake git libfluidsynth-dev libgme-dev \
libopenal-dev timidity libwildmidi-dev unzip

# Boost libraries
sudo apt-get install libboost-all-dev

Follow these instructions to create a Vizdoom environment

conda create --name vizdoom python=3.7
conda activate vizdoom
conda install tqdm
conda install numpy
conda install -c conda-forge scikit-image

If you have a dedicated GPU, follow these instructions to install Tensorflow optimized for GPU usage

conda install tensorflow-gpu==1.14.0
conda install -c numba cudatoolkit

If you do not have a dedicated GPU, follow these instructions to install Tensorflow optimized for CPU usage

conda install tensorflow==1.14.0

Follow these instructions to install vizdoom

conda skeleton pypi vizdoom --version=1.1.7 --python=3.7
conda build vizdoom --python=3.7
conda install --use-local vizdoom

**Comment by roscibely** [comment]
I'm with the same problem: "AttributeError: module 'vizdoom' has no attribute 'DoomGame'". I installed on windows. 
I put vizdoom directory into Anaconda sitepackages.

**Comment by mwydmuch** [comment]
Old issues + a lot of Windows issues were resolved in the last years.
