### ISSUE TITLE
it takes a long time to add bot

### ISSUE THREAD

**Issue by Jeeeeeiel** [Farama-Foundation/ViZDoom#269]
i want to add several bots in cig.wad, but i found it only add one bot at a time(maybe takes 10-20 frames), and the whole process(adding several bots) won't complete until the game reaches the several hundred frames.Does anyone know how to fix it?

**Comment by Jeeeeeiel** [comment]
how can i make "addbot" effective immediately?Does anyone knows?

**Comment by jkterry1** [comment]
Hey,

I'm closing this GitHub issue due to inactivity
