### ISSUE TITLE
Notes on running ViZDoom inside Docker container on Ubuntu 16.04

### ISSUE THREAD

**Issue by michaelkrax** [Farama-Foundation/ViZDoom#307]
While trying to get ViZDoom to run in a docker container as outlined in https://github.com/mihahauke/vizdoom_cig2017 i ran into a few obstacles. 

They would apply to generic use of ViZDoom in Docker so i am posting them here:

- The GUI forwarding seems to fail on Ubuntu 16.04 if game.add_game_args("+vid_forcesurface 1") isn't called before game.init()

- While the GUI forwarding works this way it still did not allow me to show images via OpenCV via imshow(). This required adding "--ipc host" as a parameter when starting the Docker container. In the CIG2017 template that would be in the last line of run.sh after "--privileged". This seems to be due to the MIT-SHM extension: https://github.com/osrf/docker_images/issues/21

I am still getting a bunch of other error messages but they do not need to impact general functionality besides sound: 

Gtk-Message: Failed to load module "canberra-gtk-module"
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

Interestingly enough  the docker container manages to crash the audio subsystem of the _host_ somehow. I actually need to reboot to get audio on the host back after launching the docker container with both GUI sharing workarounds enabled. 

EDIT: By disabling "SHM" support in /etc/pulse/client.conf i am able to protect pulseaudio on the host from crashing. It seems there are ways to make pulseaudio communication to the host work like https://github.com/TheBiggerGuy/docker-pulseaudio-example but that seems overkill as audio isn't needed for most ViZDoom stuff anyway. Would be great to have a working dockerfile that supports audio for ViZDoom on Ubuntu (anyone?) but i will likely stop here. If anyone accidentally breaks pulseaudio on the host you can always use "pulseaudio -k" on the host to kill the service to get host audio back.

**Comment by jkterry1** [comment]
Hey,

Thanks a ton for reporting this. I apologize that this issue was never replied to, but I'm going to close it now since it's been ~6 years and this release of Ubuntu is no longer supported
