### ISSUE TITLE
ZDoom crashing

### ISSUE THREAD

**Issue by dejandenib** [Farama-Foundation/ViZDoom#326]
This question is more concerning about ZDOOM, not VizDoom, but maybe someone can give me the right direction on how to solve this.
I am working on a High Performance Computing Environment, built on CENT OS 7.
I am using the latest version of Vizdoom, compiled myself.
On this remote cluster, I don't have root sudo access, so it was a bit difficult to set and install everything. Sometimes I had to kindly ask the administators and technical support, to install some dependencies for me.

When I launch the basic example, on how to run vizdoom, it crashes with the output:
It crashes with output:
*** Fatal Error ***
Address not mapped to object (signal 11)
Address: 0x8

Generating zdoom-crash.log and killing process 19108, please wait... warning: File "/rwthfs/rz/SW/gcc/CENTOS-7.3/5.3.0/lib64/libstdc++.so.6.0.21-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.py".
zsh: killed     ./zdoom -nomusic
kn797380@login-g:~/zdoom/build[513]$ Warning: Missing charsets in String to Font
Set conversion

=============================
I am attaching the created crash log to this, which has additional information.​
[zdoom crash log](https://github.com/mwydmuch/ViZDoom/files/2135034/zdoom.crash.log)

I get the same error even without Vizdoom, when I run ./zdoom inside zdoom/build.

Can you please help me?

**Comment by mwydmuch** [comment]
Old issue, closing.
