### ISSUE TITLE
C++ Windows Releases

### ISSUE THREAD

**Issue by OlegJakushkin** [Farama-Foundation/ViZDoom#328]
### Issues
It is hard to [build ](https://ci.appveyor.com/project/OlegJakushkin/vizdoom) for Windows, yet it is possible. I had to[ change 6 files ](https://github.com/OlegJakushkin/ViZDoom/blob/master/.appveyor.yml)for it to be doable on my machine:
 - *Big problems:*
 - Unresolved externals [part 1](https://ci.appveyor.com/project/OlegJakushkin/vizdoom/build/105/job/oysxxesh4r8ewsd8#L70219):  LNK2019:  unresolved external symbol "class FBoolCVar am_drawmapback" and LNK2019: unresolved external symbol "class FIntCVar am_showtriggerlines" (I commented them out yet it is not a proper fix)
 - Unresolved externals [part 2](https://ci.appveyor.com/project/OlegJakushkin/vizdoom/build/115/job/3t98f9a3qy43mul8#L70243) LNK2019: unresolved external symbol "class FBoolCVar viz_am_center"  and LNK2019: unresolved external symbol "class FFloatCVar viz_am_scale" (I commented them out yet it is not a proper fix)
 - *Minor issues:*
 - re2c fails for me every time - had to pregenerate file and [store it in repo](https://github.com/OlegJakushkin/ViZDoom/blob/master/src/vizdoom/src/sc_man_scanner.h)
 - Cmake boost find_package always fails for me so I needed an alternative (add Boost include paths and Libs folder manually).
 - I needed to build for VS2012 (VC11) and there is only one line that needs to be [changed for it](https://github.com/OlegJakushkin/ViZDoom/commit/e98f9df5ccebb37bdecd70f73dbd90be0cfb2eb1).

Thanks!

My appveyor build has artifacts[ that one can download to play around for VS2012, VS2013, VS2015, VS2017 (static libvizdoom for windows + vizdoom.exe for win32)](https://ci.appveyor.com/project/OlegJakushkin/vizdoom/build/122)

**Comment by mwydmuch** [comment]
Closing, Windows wheels are available via PyPI for a while now.
