### ISSUE TITLE
Vizdoom and pytorch crashed when import together

### ISSUE THREAD

**Issue by Trinkle23897** [Farama-Foundation/ViZDoom#335]
* description of an issue,

```
>>> import vizdoom
>>> import torch
Segmentation fault (core dumped)
```

detail: 
```
n+e:/test/viz_2018 gdb python

GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1

(gdb) run test.py 
Starting program: /home/likewise-open/wengjiayi/anaconda3/bin/python test.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007fffe51284da in pybind11::detail::make_new_python_type (rec=...) at /pytorch/third_party/pybind11/include/pybind11/detail/class.h:564
564     /pytorch/third_party/pybind11/include/pybind11/detail/class.h: No such file or directory.
(gdb) 
```

```
>>> import torch
>>> import vizdoom
Segmentation fault (core dumped)
```

detail: 
```
n+e:/test/viz_2018 gdb python                                                                                                                                                                                        

GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1

(gdb) run test.py 
Starting program: /home/likewise-open/wengjiayi/anaconda3/bin/python test.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007fffb948210c in ?? () from /home/likewise-open/wengjiayi/anaconda3/lib/python3.6/site-packages/vizdoom/vizdoom.so
(gdb) 
```

* ViZDoom version you are using,

tested on 1.1.5 and 1.1.6, all of them crashed

* information about your OS platform, distribution and environment (GCC, Python, Java, Lua versions etc.),

os: ubuntu 14.04
python: python2.7.6  python3.5.5 python3.6.4 
gcc: 4.8.4
pytorch version: 0.4.0
cuda: 8.0
nvidia driver version: 384.130
cmake: I have tried 2.8 and 3.12, change cmake version did not work for this issue

* if you have a problem with installation/building, post pip, CMake and Make output etc.,

installed successful both `pip install vizdoom` and `git checkout 1.1.6; pip install .`

* if you encountered a crash, post `vizdoom-crash.log` that should be created in your working directory,

crashed immediately, I can't find the log file

* if you encountered a crash or bug, provide information about scenarios you are using and configuration of the ViZDoom environment,

no scenarios... I don't have time to create a game, and it crashed.

* any additional information, configuration, code or data that might be helpful.

When I don't import torch, i.e., import tensorflow and vizdoom, it works fine.

**Comment by Trinkle23897** [comment]
I replace torch-0.4 to torch-0.3.1 and import successfully. So this issue is pytorch0.4 's bug?

**Comment by Trinkle23897** [comment]
I also tested on other people's laptop (only CPU), all of them works fine on pytorch0.4+vizdoom. I guess it is regarded to the pytorch0.4 GPU version.

**Comment by Miffyli** [comment]
Interesting. We are using pytorch 0.4 (CUDA 9.1, if I recall correctly) with vizdoom currently and we have not had any trouble (Ubuntu 16.04 machines, Python 3.5, ViZDoom 1.1.4 and 1.1.5). However we do not use anaconda, which has caused some trouble with ViZDoom in the past.

@mwydmuch ?

**Comment by Trinkle23897** [comment]
Yeah, I agree with you. Just now I have tested on my roommate's computer, ubuntu16.04 + GTX1063, both python2 and python3 works fine. On my ubuntu 1404, I tested on Anaconda(3.6.4), and free-of anaconda(3.5.5 and 2.7), all of them crashed. Sigh

**Comment by Trinkle23897** [comment]
I didn't like anaconda. But to reveal this bug, I installed Anaconda unwillingly after all of the python version have crashed...

**Comment by mwydmuch** [comment]
Old issue, closing.
