### ISSUE TITLE
using Pkg missing from Building instructions

### ISSUE THREAD

**Issue by Gadgeteering** [Farama-Foundation/ViZDoom#349]
### Questions, features suggestions and requests

If you have a question, features suggestions or requests, do not hesitate to ask.
However, you can check **[FAQ](doc/FAQ.md)** section and already existing issues with "question" tag ([is:issue label:question](https://github.com/mwydmuch/ViZDoom/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aquestion)) first.

### Issues

If you encountered an issue, please post the following things:
* description of an issue,
* ViZDoom version you are using,
* information about your OS platform, distribution and environment (GCC, Python, Java, Lua versions etc.),
* if you have a problem with installation/building, post pip, CMake and Make output etc.,
* if you encountered a crash, post `vizdoom-crash.log` that should be created in your working directory,
* if you encountered a crash or bug, provide information about scenarios you are using and configuration of the ViZDoom environment,
* any additional information, configuration, code or data that might be helpful.

Thanks!

**Comment by Gadgeteering** [comment]
After opening Julia you need to execute using Pkg before Pkg.add("CxxWrap")

**Comment by mwydmuch** [comment]
This is an old issue, closing.
