### ISSUE TITLE
Black screen when running the environment

### ISSUE THREAD

**Issue by rohitrp** [Farama-Foundation/ViZDoom#358]
I tried running basic.py, but I get black screen. There is sound, but no graphics. Same thing is happening with some custom code that I tried to run. I am running it on a 2018 Macbook Pro with mac OS Mojave. I am not sure how to debug this issue. I tried to find solutions for this, but couldn't find any similar issues. 

I am using Python 3.6. I tried two ways of installing it - one using `pip install vizdoom`, and cloning the current repo and executing `pip install .`

**Comment by mihahauke** [comment]
@mwydmuch Does it work for you on Mojave :D? I wound't be surprised if they had messed up something there that interferes with doom.

**Comment by mwydmuch** [comment]
Closing this old issue. I've never encountered this issue, but it was probably fixed when we switched to SDL2 backend for macOS.
