### ISSUE TITLE
How to make bots only hate agent

### ISSUE THREAD

**Issue by acrushdjn** [Farama-Foundation/ViZDoom#368]
Hi,
I added 5 bots in the map, but bots will hate each other, is there a way to make bots only hate the agent/player? because I want to do 1VS5 senario.

**Comment by Miffyli** [comment]
Do you mean NPC monsters or player bots (added with `addbot` command)? For the first, you can set the Hate towards player in ACS scripts with [Thing_Hate](https://zdoom.org/wiki/Thing_Hate) command. You can find examples of using this in the deathmatch_shotgun.wad you shared in #366

**Comment by acrushdjn** [comment]
@Miffyli I mean player bots(added with addbot command)

**Comment by Miffyli** [comment]
For that I do not know a way to make them target any specific player. As far as I know, they have been coded to win the game of deathmatch, i.e. scoring as many frags as possible.

**Comment by mihahauke** [comment]
@acrushdjn I am pretty sure it is imporrible at this point. Perhaps launching team deathmatch will achieve something in this regard?

**Comment by mwydmuch** [comment]
I'm closing this old issue. I'm sorry I haven't answered this one before. There is no easy solution to that problem. One thing that was used by others in the past was to create player-look-alike enemies and create a script to respawn them on the map.
