### ISSUE TITLE
screen/window alignment problem

### ISSUE THREAD

**Issue by krille0x7c2** [Farama-Foundation/ViZDoom#371]
* pip install git+https://github.com/mwydmuch/ViZDoom
* macOS Mojave v 10.14.3 on macbook pro 2017
* run some python example e.g. basic.py.
* dude split in half [problem screen recording](https://imgur.com/a/tuTCgf6)

I haven't tried to run it on any other machine so i don't know if this is a OSX specific problem or not.

**Comment by mwydmuch** [comment]
Hello @krille0x7c2, thank you for reporting the problem, looks like this is SDL2 and Mojave related, upgrading SDL2 to version 2.0.9 (can be done via brew `brew upgrade sdl2`) fix the problem.

**Comment by mwydmuch** [comment]
I guess this problem was solved, so I'm closing this old issue.
