### ISSUE TITLE
vizdoom installation failed? please help, see the below message, whats wrong with the installation?

### ISSUE THREAD

**Issue by adil25** [Farama-Foundation/ViZDoom#374]
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-be623tmj/vizdoom/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-562o9z9y/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-be623tmj/vizdoom/

**Comment by Miffyli** [comment]
Could you include Python version used, the operating system etc etc? Did you install the [dependencies](https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md#linux_deps) (if you are on Linux/Mac)?

**Comment by adil25** [comment]
Python version 3, Ubuntu 16.04 LTS, yes i also installed dependencies on my linux-ubuntu.
    On Tuesday, March 26, 2019, 7:57:43 PM GMT+8, Anssi <notifications@github.com> wrote:  
 
 
Could you include Python version used, the operating system etc etc? Did you install the dependencies (if you are on Linux/Mac)?

**Comment by Miffyli** [comment]
Hmm. Could you also include the whole output after you start installing vizdoom?

**Comment by pierresegonne** [comment]
Hi i'm experimenting the same problem, (ubuntu 16.04, python 3.6.7).
All dependencies listed on the building.md have been installed.
The error is caused by 
```
Make Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
      Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
      (Required is at least version "3.6")
```

**Comment by jkterry1** [comment]
Hey,

It's been around 5 years so I'm going to close this issue due to inactivity, if the issue reoccurs please let us know :)
