### ISSUE TITLE
Spawning objects and agent reduces environment speed

### ISSUE THREAD

**Issue by joshim5** [Farama-Foundation/ViZDoom#388]
The environment speed (fps) reduces considerably when spawning the agent and objects at each timestep. We are doing this in order to write custom environment dynamics (e.g. have agent move along a grid) and interactions (e.g. object changes when agent co-locates with it).

We need the environment to go much faster in order to do RL with it. We use ACS/pukename to spawn the objects in the desired locations. Is there a way to do this faster?

**Comment by mwydmuch** [comment]
This is an old issue, so I'm closing it. The short answer is that spawning a lot of objects in each frame as expected can hurt performance significantly. I think there is no method to do it in a much more efficient way.
