### ISSUE TITLE
Why different total steps?

### ISSUE THREAD

**Issue by JackieTseng** [Farama-Foundation/ViZDoom#395]
Hi, I have set total steps as `21000` in the `.cfg` file. However, the game always ends by calling `game.is_episode_finished()` before 21000 steps. Any ideas?

**Comment by Miffyli** [comment]
Do you mean `episode_timeout` variable in the `.cfg` files? 

This timeout is measured in game frames, not agent steps. I.e. if you have frame-skip of 4 frames (specified in `advance_action` or `make_actions`), the total number of agent steps will be `21000 / 4 = 5250`.

**Comment by JackieTseng** [comment]
Yep, I use `episode_timeout=21000` without frame-skip. However, it's strange that the game usually ends less than 21000 steps (e.g., 18000+ steps).

**Comment by Miffyli** [comment]
Try checking the tick number in game state to see if indeed the internal game only runs for the 18k steps, i.e. `game_state.tic`. 
 
Can you share the scenario file/config and the code used to run the game? There could be some other episode-finishing trigger happening before the timeout (e.g. death in some scenarios).

**Comment by alex-petrenko** [comment]
Are you running some kind of multiplayer scenario by any chance? There's another option that can terminate the episode early, which is +timelimit.
You can specify it when you start the environment. Check if it isn't set to some low value (21000 steps should be about 10 minutes).

```
self.game.add_game_args(
                f'-host {self.num_players} -port {port} '
                '-deathmatch '  # Deathmatch rules are used for the game.                
                '+timelimit 5.0 '  # The game (episode) will end after this many minutes have elapsed.
                '+sv_forcerespawn 1 '  # Players will respawn automatically after they die.
                '+sv_noautoaim 1 '  # Autoaim is disabled for all players.
                '+sv_respawnprotect 1 '  # Players will be invulnerable for two second after spawning.
                '+sv_spawnfarthest 1 '  # Players will be spawned as far as possible from any other players.
                '+sv_nocrouch 1 '  # Disables crouching.
                '+viz_respawn_delay 0 '  # Sets delay between respanws (in seconds).
            )
```

**Comment by JackieTseng** [comment]
@Miffyli Hi, I have printed `tic` which ends at `21000`. It seems right. I use `skip_frame=4` to run the game. However, `total_steps` usually ends less than 5250, mostly equal to 4200-4900. My scenario file and main code are listed below.
```
self.game.add_game_args(
    "-host 1 "
    "-deathmatch "
    "+timelimit 10.0"
    "+sv_forcerespawn 1 "
    "+sv_noautoaim 1 "
    "+sv_respawnprotect 1 "
    "+sv_spawnfarthest 1 "
    "+sv_nocrouch 1 "
    "+viz_respawn_delay 10 "
    "+viz_nocheat 0 "
    "+name AI +colorset 0"
)

while not self.game.is_episode_finished():
    step()
self.game.new_episode()

```

```
doom_scenario_path = cig2017_track1.wad
doom_map = map01


# Rendering options
screen_resolution = RES_640X480
screen_format = CBCGCR
render_hud = true
render_crosshair = true
render_weapon = true
render_decals = false
render_particles = false
window_visible = false

# start, end in tics
episode_start_time = 10
episode_timeout = 21000

# Available buttons
available_buttons = 
{
    ATTACK
    USE

    TURN_LEFT
    TURN_RIGHT
    MOVE_RIGHT
    MOVE_LEFT
    MOVE_FORWARD
    MOVE_BACKWARD

    TURN_LEFT_RIGHT_DELTA
    LOOK_UP_DOWN_DELTA
}

available_game_variables =
{
    HEALTH
    AMMO
}

game_args += +sv_noautoaim 1
game_args += +sv_respawnprotect 1
game_args += +sv_forcerespawn 1
game_args += +sv_unlimited_pickup 1

mode = PLAYER
doom_skill = 3
```
@alex-petrenko Yes, I am running multi-player version. As you can see, I set both 'episode_timeout=21000' in `.cfg` file and 'timelimit=10.0' in the running code.

Any idea to solve this problem?

**Comment by Miffyli** [comment]
One more plotting request: Try recording the difference in `tic`s and plotting it out to see if they vary (they should always be four with `frame_skip=4`). Something like:

```python
tics = []
while not self.game.is_episode_finished():
    #Choosing action, stepping game, getting game_state
    tics.append(game_state.tic)
diff_tics = np.diff(np.array(tics))
pyplot.plot(diff_tics)
pyplot.show()
```

**Comment by alex-petrenko** [comment]
Not sure... never had this problem. Any chance you have some non-trivial code in the scenario ACS script? I think it might be possible to end the episode via ACS script. You can look at it by opening your WAD file in Slade.

Another hypothesis: can there be fraglimit somewhere? This could explain why the episode duration is random.

**Comment by JackieTseng** [comment]
@Miffyli I tried twice and got following results.
Steps=4637 with skip=4
![Figure_4637](https://user-images.githubusercontent.com/7310697/60578767-5fe49200-9db4-11e9-9465-615c03e7e957.png)
Steps=4986 with skip=4
![Figure_4986](https://user-images.githubusercontent.com/7310697/60578783-68d56380-9db4-11e9-92ce-8a58c1c2265e.png)
Any ideas?

**Comment by Miffyli** [comment]
That (the spikes) shouldn't be happening, but I have no idea what could be causing it. Could you share the scenario file and the Python code for further debugging? Seems like this is a bug of sorts, or at least a "feature" that should be documented somewhere.

**Comment by mwydmuch** [comment]
I'm sorry I missed this issue when it was discussed. I have my suspicion why it's so, and it's quite simple. In @JackieTseng's code, there is `+viz_respawn_delay 10` argument, which sets respawn time to 10 seconds. Not sure what is in `step()` function, but if the code was using following code snippet (as in all cig examples):

```
if game.is_player_dead():
    game.respawn_player()
```

Then `game.respawn_player()` makes the controller wait for the respawn, which in this case was 10 seconds, and skips all the steps when the agent is dead, making a smaller number of total steps expected. On the other hand, if `game.respawn_player()` was not used, we should observe a constant number of steps.

I'm closing this issue since it's very old.
