### ISSUE TITLE
Team Deathmatch Python

### ISSUE THREAD

**Issue by madaanpulkit** [Farama-Foundation/ViZDoom#420]
How to play a team deathmatch in python?
I want to choose actions for all my team members.

**Comment by Miffyli** [comment]
See examples on [how to host a server](https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/cig_multiplayer_host.py) and [connect to it from other clients](https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/cig_multiplayer.py). You can start these instances in same Python script with e.g. `Thread`s or `multiprocessing.Process`es.

See this related discussion: #391

**Comment by mwydmuch** [comment]
The question was answered. I'm closing this issue.
