### ISSUE TITLE
Collecting Episodes from an in-game Bot

### ISSUE THREAD

**Issue by agopal42** [Farama-Foundation/ViZDoom#429]
How can I collect episodes (instead of simply using a random policy agent) from an in-game bot for scenarios such as TakeCover, Defend the Center, Deadly Corridor etc? Is there a feature that allows me to do this?  Thank you.

**Comment by Miffyli** [comment]
Hmm there could be a way to do this with some hackery, but no, there is no built-in/premade solution for this in ViZDoom. I do not think they would work too well for those scenarios, either, as they make so many restrictions on the player.

But, if you want to have some decent demonstrations quickly, you could try using the [example learning code](https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/learning_pytorch.py) to train an agent and use it to record demonstrations. You could also try other RL libraries like [stable-baselines](https://github.com/hill-a/stable-baselines/) if their agents work in ViZDoom.
