### ISSUE TITLE
Finding out what a monster is attacking

### ISSUE THREAD

**Issue by arunraja-hub** [Farama-Foundation/ViZDoom#461]
Question:
How can I  find out what a monster is currently attacking in an ACS script?
 My goal is to determine if the monsters are infighting and do something if they are, like open a door.

Thanks!

**Comment by Miffyli** [comment]
I have not tested this, but you could use [`CheckActorState`](https://zdoom.org/wiki/CheckActorState) to check which monsters are in the "firing" state. This is commonly named "Missile", like with e.g. [Imp](https://zdoom.org/wiki/Classes:DoomImp).

**Comment by arunraja-hub** [comment]
Sorry what I meant was which actors were getting attacked by a monster. If there are monsters A,B and C and A is attacking, I want to know which of the other 2, B and C, are getting attacked

**Comment by Miffyli** [comment]
You could track actors' health (`APROP_Health`) with [`GetActorProperty`](https://zdoom.org/wiki/GetActorProperty) and track when they change. Alas, this does not tell who was attacking them, and I have not been able to find a way to specifically hook for "actor X attacked Y with Z damage" type of thing :/

**Comment by jkterry1** [comment]
Hey,

I'm closing this issue as it appears that the original question was answered :)
