### ISSUE TITLE
ValueError: setting an array element with a sequence. in learning_stable_baselines.py

### ISSUE THREAD

**Issue by zfwang615** [Farama-Foundation/ViZDoom#516]
I'm trying to use [examples/python/learning_stable_baselines.py](https://github.com/mwydmuch/ViZDoom/tree/master/examples/python/learning_stable_baselines.py). This example has some questions. By the way, `learning_pytorch.py` works well.

MY ENV INFO:
- ubuntu 20.04.5
- conda python 3.8.13
- vizdoom 1.1.14
- stable_baselines3 1.6.2

First, the env is using 'screen' instead 'rgb' now.

```
class ObservationWrapper(gym.ObservationWrapper):
...
...
    def __init__(self, env, shape=IMAGE_SHAPE):
        super().__init__(env)
        self.image_shape = shape
        self.image_shape_reverse = shape[::-1]

        # Create new observation space with the new shape
        num_channels = env.observation_space["screen"].shape[-1] # use 'screen' instead 'rgb'
        new_shape = (shape[0], shape[1], num_channels)
        self.observation_space = gym.spaces.Box(0, 255, shape=new_shape, dtype=np.uint8)

    def observation(self, observation):
        observation = cv2.resize(observation["screen"], self.image_shape_reverse) # use 'screen' instead 'rgb'
        return observation
```
After that, I got followed error: 
```
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
```
in SB3 `dummy_vec_env.py`, the error occurred`self.buf_obs[key][env_idx]=obs`
- `obs_space` is a Box(0, 255, (60, 80, 3), uint8)
- `self.keys` is None 
- `self.buf_obs[key][env_idx]` is a np.ndarray
- `obs` is a tuple

Could you give me some advice? Thanks in advance for any help.

**Comment by Miffyli** [comment]
Hey! Sounds like something has gone off with the changes for Gym support. Make sure you are using the newest code when trying things out (clone from the github), but beyond that I do not have bandwidth to debug what could have gone wrong :(.

**Comment by jkterry1** [comment]
Hey, stable baselines 3 doesn't support current versions of gym/gymnasium, but has publicly promised to soon. You can either use their beta fork with support for newer versions, wait for them to update, use an older version of this package with an older version of gym, or try cleanrl or another library instead of sb3
