### ISSUE TITLE
Create documentation in farama.org style

### ISSUE THREAD

**Issue by mwydmuch** [Farama-Foundation/ViZDoom#524]
This consists of a few subtasks:
- Create Farama-like documentation generated by sphinx.
- Figure out what is a proper way to document Gym/Gymnasium API and core API (pybind11 module) and generate sphinx docs for them (and migrate old docs to the new format).
- Have the documentation website be at .farama.org. 
- Include the standard Farama code of conduct.

**Comment by Touutae-lab** [comment]
Can you assign me for this issue ?
