### ISSUE TITLE
Cannot pickle vizdoom.vizdoom.GameState in python

### ISSUE THREAD

**Issue by WendaDeng** [Farama-Foundation/ViZDoom#534]
### Issues

I am trying to use a RL agent to interact with ViZDoom env through network. I need to serialize the game state produce by ViZDoom env and send it to agent through network. I use the python API of ViZDoom and use pickle/cloudpickle to serialize the game state. But I encounter the problem "TypeError: cannot pickle 'vizdoom.vizdoom.GameState' object". So, is it prossible to add serialize/deserialize method to support the serialization/deserialization of game state?

Additional infomation:
* OS: 5.15.0-56-generic 20.04.1-Ubuntu x86_64 GNU/Linux
* Python version: default 3.8.10
* ViZDoom version: 1.1.14

**Comment by mwydmuch** [comment]
Hi @WendaDeng thank you for opening the issue. Yes it should be possible, thank you for the suggestion, I will add it soon (after returning from my vacation on 18 February). Right now the very simple workaround is to read and write `GameState` attributes to some other packable object, e.g. dictionary.
