### ISSUE TITLE
from vizdoom import gymnasium_wrapper doesn't work

### ISSUE THREAD

**Issue by sparisi** [Farama-Foundation/ViZDoom#542]
I am trying to run the example for the gymnasium wrapper but I get

`ImportError: cannot import name 'gymnasium_wrapper' from 'vizdoom' (C:\Users\Simone\anaconda3\envs\gym\lib\site-packages\vizdoom\__init__.py)`

Running on Windows, Python 3.10, latest gymnasium is installed, and I just installed `pip install vizdoom[gym]` (tried without [gym] and still fails).

Gym wrappers work though (but `reset(seed)` doesn't work, reset is not deterministic, so I wanted to try gymnasium).

**Comment by mwydmuch** [comment]
Hi @sparisi, the version with Gymnasium support is not yet officially released (but it should be soon). At the moment, you can install it using:
```
pip install git+https://github.com/Farama-Foundation/ViZDoom.git
```

**Comment by sparisi** [comment]
Alright, thanks for the quick response!
