### ISSUE TITLE
Cannot install via pip

### ISSUE THREAD

**Issue by vosiz** [Farama-Foundation/ViZDoom#566]
I am following documentation provided to install on Windows. No success.

- Windows 7 x64
- Python 3.8.0

Here is output from console:

G:\Users\Vosiz>pip install vizdoom
Collecting vizdoom
  Using cached vizdoom-1.2.2.tar.gz (15.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy (from vizdoom)
  Obtaining dependency information for numpy from https://files.pythonhosted.org
/packages/d1/57/8d328f0b91c733aa9aa7ee540dbc49b58796c862b4fbcb1146c701e888da/num
py-1.24.4-cp38-cp38-win32.whl.metadata
  Downloading numpy-1.24.4-cp38-cp38-win32.whl.metadata (5.6 kB)
Collecting gymnasium>=0.28.0 (from vizdoom)
  Obtaining dependency information for gymnasium>=0.28.0 from https://files.pyth
onhosted.org/packages/a8/4d/3cbfd81ed84db450dbe73a89afcd8bc405273918415649ac6683
356afe92/gymnasium-0.29.1-py3-none-any.whl.metadata
  Downloading gymnasium-0.29.1-py3-none-any.whl.metadata (10 kB)
Collecting pygame>=2.1.3 (from vizdoom)
  Obtaining dependency information for pygame>=2.1.3 from https://files.pythonho
sted.org/packages/f1/ba/fe5a0ed7adc1891bba486a431271d3c422afaf00644cf77abf8521f4
4890/pygame-2.5.2-cp38-cp38-win32.whl.metadata
  Downloading pygame-2.5.2-cp38-cp38-win32.whl.metadata (13 kB)
Collecting cloudpickle>=1.2.0 (from gymnasium>=0.28.0->vizdoom)
  Using cached cloudpickle-2.2.1-py3-none-any.whl (25 kB)
Collecting typing-extensions>=4.3.0 (from gymnasium>=0.28.0->vizdoom)
  Obtaining dependency information for typing-extensions>=4.3.0 from https://fil
es.pythonhosted.org/packages/24/21/7d397a4b7934ff4028987914ac1044d3b7d52712f30e2
ac7a2ae5bc86dd0/typing_extensions-4.8.0-py3-none-any.whl.metadata
  Downloading typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Collecting farama-notifications>=0.0.1 (from gymnasium>=0.28.0->vizdoom)
  Using cached Farama_Notifications-0.0.4-py3-none-any.whl (2.5 kB)
Collecting importlib-metadata>=4.8.0 (from gymnasium>=0.28.0->vizdoom)
  Obtaining dependency information for importlib-metadata>=4.8.0 from https://fi
les.pythonhosted.org/packages/cc/37/db7ba97e676af155f5fcb1a35466f446eadc9104e25b
83366e8088c9c926/importlib_metadata-6.8.0-py3-none-any.whl.metadata
  Downloading importlib_metadata-6.8.0-py3-none-any.whl.metadata (5.1 kB)
Collecting zipp>=0.5 (from importlib-metadata>=4.8.0->gymnasium>=0.28.0->vizdoom
)
  Obtaining dependency information for zipp>=0.5 from https://files.pythonhosted
.org/packages/d9/66/48866fc6b158c81cc2bfecc04c480f105c6040e8b077bc54c634b4a67926
/zipp-3.17.0-py3-none-any.whl.metadata
  Downloading zipp-3.17.0-py3-none-any.whl.metadata (3.7 kB)
Using cached gymnasium-0.29.1-py3-none-any.whl (953 kB)
Using cached numpy-1.24.4-cp38-cp38-win32.whl (12.5 MB)
Using cached pygame-2.5.2-cp38-cp38-win32.whl (10.4 MB)
Using cached importlib_metadata-6.8.0-py3-none-any.whl (22 kB)
Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Using cached zipp-3.17.0-py3-none-any.whl (7.4 kB)
Building wheels for collected packages: vizdoom
  Building wheel for vizdoom (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for vizdoom (pyproject.toml) did not run successfully.
  │ exit code: 1
  ?─> [40 lines of output]
      running bdist_wheel
      running build
      Traceback (most recent call last):
        File "g:\users\vosiz\appdata\local\programs\python\python38-32\lib\site-
packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <
module>
          main()
        File "g:\users\vosiz\appdata\local\programs\python\python38-32\lib\site-
packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in m
ain
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "g:\users\vosiz\appdata\local\programs\python\python38-32\lib\site-
packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in b
uild_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "G:\Users\Vosiz\AppData\Local\Temp\pip-build-env-qrwlwto0\overlay\L
ib\site-packages\setuptools\build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
        File "G:\Users\Vosiz\AppData\Local\Temp\pip-build-env-qrwlwto0\overlay\L
ib\site-packages\setuptools\build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "G:\Users\Vosiz\AppData\Local\Temp\pip-build-env-qrwlwto0\overlay\L
ib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_scri
pt)
        File "G:\Users\Vosiz\AppData\Local\Temp\pip-build-env-qrwlwto0\overlay\L
ib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 194, in <module>
        File "G:\Users\Vosiz\AppData\Local\Temp\pip-build-env-qrwlwto0\overlay\L
ib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "G:\Users\Vosiz\AppData\Local\Temp\pip-build-env-qrwlwto0\overlay\L
ib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "G:\Users\Vosiz\AppData\Local\Temp\pip-build-env-qrwlwto0\overlay\L
ib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "G:\Users\Vosiz\AppData\Local\Temp\pip-build-env-qrwlwto0\overlay\L
ib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "G:\Users\Vosiz\AppData\Local\Temp\pip-build-env-qrwlwto0\overlay\L
ib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "G:\Users\Vosiz\AppData\Local\Temp\pip-build-env-qrwlwto0\overlay\L
ib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "G:\Users\Vosiz\AppData\Local\Temp\pip-build-env-qrwlwto0\overlay\L
ib\site-packages\wheel\bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "G:\Users\Vosiz\AppData\Local\Temp\pip-build-env-qrwlwto0\overlay\L
ib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "G:\Users\Vosiz\AppData\Local\Temp\pip-build-env-qrwlwto0\overlay\L
ib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "G:\Users\Vosiz\AppData\Local\Temp\pip-build-env-qrwlwto0\overlay\L
ib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 124, in run
      RuntimeError: VIZDOOM_BUILD_GENERATOR_NAME is not set
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem wit
h pip.
  ERROR: Failed building wheel for vizdoom
Failed to build vizdoom
ERROR: Could not build wheels for vizdoom, which is required to install pyprojec
t.toml-based projects

Thanks!

**Comment by vosiz** [comment]
I see...

if platform.startswith("win"):
            generator = os.getenv("VIZDOOM_BUILD_GENERATOR_NAME")
            if not generator:
                raise RuntimeError(
                    "VIZDOOM_BUILD_GENERATOR_NAME is not set"
                )  # TODO: Improve  **<======================================**

**Comment by mwydmuch** [comment]
Hi @vosiz, I made a new release a day ago, and the Windows pre-build wheels are not available yet (as the process is not automated). Please install vizdoom==1.2.1 or wait one more day for the binary release for Windows on PyPI. And I apologize for the inconvenience.

**Comment by mwydmuch** [comment]
Hi again, @vosiz. I am letting you know that Windows binary wheels are now available via PyPI, so you should be able to install the newest 1.2.2 release without the problem. We will add a more informative warning when pip tries to build a Windows version from the source (which cannot be done without proper dependencies and Visual Studio C++ compiler). 

By the way, you wrote that you use Windows 7, so please keep in mind that Windows releases are only tested on Windows 10.

**Comment by mwydmuch** [comment]
One more warning. From the log you posted, I noticed that you are using a 32-bit version of Python (wheels has a win32.whl suffix). So, this release won't work for you, as we only support 64-bit versions. Please update your Python to the 64-bit version if you want to use ViZDoom on Windows or use the Linux version via WSL or Docker.

**Comment by vosiz** [comment]
> One more warning. From the log you posted, I noticed that you are using a 32-bit version of Python (wheels has a win32.whl suffix). So, this release won't work for you, as we only support 64-bit versions. Please update your Python to the 64-bit version if you want to use ViZDoom on Windows or use the Linux version via WSL or Docker.

Ty, will update aswell.
