### ISSUE TITLE
Can I use VizDoom in other FPS games?

### ISSUE THREAD

**Issue by XliOK** [Farama-Foundation/ViZDoom#571]
Can I use VizDoom in other FPS games? For example, in CS 1.6 or other FPS combat games, is there any information on this?

**Comment by mwydmuch** [comment]
Hi @XliOK, not really. ViZDoom is designed to integrate with the ZDoom engine and only works with a few games supported by this engine (Doom, Doom 2, Heretic, Hexen, Strife, etc.).

**Comment by XliOK** [comment]
> 你好@XliOK， 并不真地。ViZDoom 旨在与 ZDoom 引擎集成，并且仅适用于该引擎支持的少数游戏（Doom、Doom 2、Heretic、Hexen、Strife 等）。

Are there other open-source codes available for training AI in FPS games?

**Comment by mwydmuch** [comment]
If you want to use commercial games, then number of libraries is very limited. I would recommend looking into https://github.com/minerllabs/minerl, which is based on Minecraft (not really a true FPS, but it's a commercial game).

If you don't care about the game being commercial and you are just looking for FPP environments, then I recommend checking:
- https://github.com/Farama-Foundation/Miniworld
- https://github.com/google-deepmind/lab
- https://github.com/unrealcv/unrealcv
