### ISSUE TITLE
First Time User Encountering Pip Install Error M1

### ISSUE THREAD

**Issue by DiggetyDoo** [Farama-Foundation/ViZDoom#572]
I've tried the solutions I found online to no avail, including the line commenting found in #485. The only thing I have come up with that may be causing the error is that I'm on macOS version 14.2 Beta (23C5030f).
I'm getting the following error when I try to run pip install vizdoom:
(doom) odorf:ViZDoom thaddeuskopczynski$ pip install .
Processing /Users/thaddeuskopczynski/PersonalProgramming/PersonalPython/doom/ViZDoom
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy
  Using cached numpy-1.26.2-cp311-cp311-macosx_11_0_arm64.whl (14.0 MB)
Collecting gymnasium>=0.28.0
  Using cached gymnasium-0.29.1-py3-none-any.whl (953 kB)
Collecting pygame>=2.1.3
  Using cached pygame-2.5.2-cp311-cp311-macosx_11_0_arm64.whl (12.2 MB)
Collecting cloudpickle>=1.2.0
  Using cached cloudpickle-3.0.0-py3-none-any.whl (20 kB)
Collecting typing-extensions>=4.3.0
  Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Collecting farama-notifications>=0.0.1
  Using cached Farama_Notifications-0.0.4-py3-none-any.whl (2.5 kB)
Building wheels for collected packages: vizdoom
  Building wheel for vizdoom (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for vizdoom (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [256 lines of output]
      running bdist_wheel
      running build
      Running cmake with arguments: ['cmake', '-DCMAKE_BUILD_TYPE=Release', '-DBUILD_PYTHON=ON', '-DBUILD_PYTHON_VERSION=3.11', '-DPython_ROOT_DIR=/Users/thaddeuskopczynski/PersonalProgramming/PersonalPython/doom/doom/bin', '-DPython_FIND_STRATEGY=LOCATION']
      CMake Warning:
        No source or binary directory provided.  Both will be assumed to be the
        same as the current working directory, but note that this warning will
        become a fatal error in future CMake releases.
      
      
      -- The C compiler identification is AppleClang 15.0.0.15000040
      -- The CXX compiler identification is AppleClang 15.0.0.15000040
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found Boost: /usr/local/lib/cmake/Boost-1.83.0/BoostConfig.cmake (found suitable version "1.83.0", minimum required is "1.53") found components: filesystem thread system date_time chrono regex iostreams
      -- Found Threads: TRUE
      -- Found BZip2: /Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/lib/libbz2.tbd (found version "1.0.8")
      -- Looking for BZ2_bzCompressInit
      -- Looking for BZ2_bzCompressInit - found
      -- Found JPEG: /usr/local/lib/libjpeg.dylib (found version "80")
      -- Found ZLIB: /Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/lib/libz.tbd (found version "1.2.12")
      -- Could NOT find GME (missing: GME_LIBRARIES GME_INCLUDE_DIR)
      -- Using system zlib
      -- Using system jpeg library
      -- Using system bzip2 library
      -- Using internal gme library
      -- Looking for strdup
      -- Looking for strdup - found
      -- Looking for strndup
      -- Looking for strndup - found
      -- Looking for sys/types.h
      -- Looking for sys/types.h - found
      -- Looking for stdint.h
      -- Looking for stdint.h - found
      -- Looking for stddef.h
      -- Looking for stddef.h - found
      -- Check size of char
      -- Check size of char - done
      -- Check size of short
      -- Check size of short - done
      -- Check size of int
      -- Check size of int - done
      -- Check size of long
      -- Check size of long - done
      -- /Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/include
      -- /Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/include
      -- /Users/thaddeuskopczynski/PersonalProgramming/PersonalPython/doom/ViZDoom/src/vizdoom/lzma/C
      -- Looking for itoa
      -- Looking for itoa - not found
      -- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
      -- Found SDL2: /usr/local/lib/libSDL2main.a;/usr/local/lib/libSDL2.dylib;-framework Cocoa
      -- Found OpenAL: /usr/local/opt/openal-soft/lib/libopenal.dylib
      -- Could not find FMOD include files
      -- Found SndFile: /usr/local/lib/libsndfile.dylib
      -- Found MPG123: /usr/local/lib/libmpg123.dylib
      -- Could NOT find FluidSynth (missing: FLUIDSYNTH_LIBRARIES FLUIDSYNTH_INCLUDE_DIR)
      -- Looking for filelength
      -- Looking for filelength - not found
      -- Looking for strupr
      -- Looking for strupr - not found
      -- Looking for stricmp
      -- Looking for stricmp - not found
      -- Looking for strnicmp
      -- Looking for strnicmp - not found
      -- Looking for clock_gettime in rt
      -- Looking for clock_gettime in rt - not found
      -- Looking for clock_gettime
      -- Looking for clock_gettime - found
      -- Performing Test HAS_VA_COPY
      -- Performing Test HAS_VA_COPY - Success
      -- Found Boost: /usr/local/lib/cmake/Boost-1.83.0/BoostConfig.cmake (found version "1.83.0") found components: thread system date_time chrono
      -- Fluid synth libs: FLUIDSYNTH_LIBRARIES-NOTFOUND
      -- Specified Python version to use: 3.11
      -- pybind11 v2.11.1
      CMake Warning (dev) at src/lib_python/pybind11/tools/FindPythonLibsNew.cmake:98 (find_package):
        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
        are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
        the cmake_policy command to set the policy and suppress this warning.
      
      Call Stack (most recent call first):
        src/lib_python/pybind11/tools/pybind11Tools.cmake:50 (find_package)
        src/lib_python/pybind11/tools/pybind11Common.cmake:188 (include)
        src/lib_python/pybind11/CMakeLists.txt:210 (include)
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      -- Found PythonInterp: /Users/thaddeuskopczynski/PersonalProgramming/PersonalPython/doom/doom/bin/python (found suitable version "3.11.2", minimum required is "3.11")
      -- Found PythonLibs: /Library/Frameworks/Python.framework/Versions/3.11/lib/libpython3.11.dylib
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- Performing Test HAS_FLTO_THIN
      -- Performing Test HAS_FLTO_THIN - Success
      -- Configuring done (3.7s)
      -- Generating done (0.1s)
      CMake Warning:
        Manually-specified variables were not used by the project:
      
          Python_FIND_STRATEGY
          Python_ROOT_DIR
      
      
      -- Build files have been written to: /Users/thaddeuskopczynski/PersonalProgramming/PersonalPython/doom/ViZDoom
      [  0%] Linking C executable ../../../../bin/lemon
      [  0%] Linking C executable ../../../../bin/updaterevision
      [  1%] Linking C static library liblzma.a
      [  1%] Linking CXX static library libgme.a
      /Users/thaddeuskopczynski/PersonalProgramming/PersonalPython/doom/ViZDoom/bin
      [  1%] Built target updaterevision
      [  4%] Built target lzma
      [  4%] Built target lemon
      [  4%] Linking CXX executable ../../../../bin/re2c
      [  4%] Linking C static library libgdtoa.a
      [  5%] Linking C executable ../../../../bin/zipdir
      [ 14%] Built target gme
      [ 14%] Linking CXX static library bin/libvizdoom.a
      [ 14%] Linking CXX shared library bin/libvizdoom.dylib
      [ 16%] Built target re2c
      [ 17%] Built target gdtoa
      [ 17%] Building C object src/vizdoom/dumb/CMakeFiles/dumb.dir/src/helpers/resampler.c.o
      ld: warning: ignoring file '/usr/local/Cellar/boost/1.83.0/lib/libboost_filesystem-mt.dylib': found architecture 'x86_64', required architecture 'arm64'
      ld: warning: ignoring file '/usr/local/Cellar/boost/1.83.0/lib/libboost_thread-mt.dylib': found architecture 'x86_64', required architecture 'arm64'
      ld: warning: ignoring file '/usr/local/Cellar/boost/1.83.0/lib/libboost_system-mt.dylib': found architecture 'x86_64', required architecture 'arm64'
      ld: warning: ignoring file '/usr/local/Cellar/boost/1.83.0/lib/libboost_date_time-mt.dylib': found architecture 'x86_64', required architecture 'arm64'
      ld: warning: ignoring file '/usr/local/Cellar/boost/1.83.0/lib/libboost_chrono-mt.dylib': found architecture 'x86_64', required architecture 'arm64'
      ld: warning: ignoring file '/usr/local/Cellar/boost/1.83.0/lib/libboost_regex-mt.dylib': found architecture 'x86_64', required architecture 'arm64'
      ld: warning: ignoring file '/usr/local/Cellar/boost/1.83.0/lib/libboost_atomic-mt.dylib': found architecture 'x86_64', required architecture 'arm64'
      ld: warning: ignoring file '/usr/local/Cellar/boost/1.83.0/lib/libboost_iostreams-mt.dylib': found architecture 'x86_64', required architecture 'arm64'
      [ 17%] Built target zipdir
      ld: Undefined symbols:
        boost::filesystem::detail::current_path(boost::system::error_code*), referenced from:
            vizdoom::initializeThisSharedObjectPath() in ViZDoomPathHelpers.cpp.o
        boost::filesystem::detail::symlink_status(boost::filesystem::path const&, boost::system::error_code*), referenced from:
            vizdoom::relativePath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in ViZDoomPathHelpers.cpp.o
        boost::filesystem::detail::path_algorithms::compare_v3(boost::filesystem::path const&, boost::filesystem::path const&), referenced from:
            vizdoom::relativePath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in ViZDoomPathHelpers.cpp.o
            vizdoom::relativePath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in ViZDoomPathHelpers.cpp.o
            vizdoom::relativePath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in ViZDoomPathHelpers.cpp.o
            vizdoom::relativePath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in ViZDoomPathHelpers.cpp.o
        boost::filesystem::detail::path_algorithms::filename_v3(boost::filesystem::path const&), referenced from:
            vizdoom::relativePath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in ViZDoomPathHelpers.cpp.o
            vizdoom::relativePath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in ViZDoomPathHelpers.cpp.o
        boost::filesystem::detail::path_algorithms::extension_v3(boost::filesystem::path const&), referenced from:
            vizdoom::fileExtension(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in ViZDoomPathHelpers.cpp.o
            vizdoom::hasExtension(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in ViZDoomPathHelpers.cpp.o
            vizdoom::checkFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in ViZDoomPathHelpers.cpp.o
        boost::filesystem::detail::path_algorithms::increment_v3(boost::filesystem::path_detail::path_iterator&), referenced from:
            vizdoom::relativePath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in ViZDoomPathHelpers.cpp.o
        boost::filesystem::detail::path_algorithms::remove_filename_v3(boost::filesystem::path&), referenced from:
            vizdoom::relativePath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in ViZDoomPathHelpers.cpp.o
        boost::filesystem::detail::path_algorithms::find_parent_path_size(boost::filesystem::path const&), referenced from:
            vizdoom::relativePath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in ViZDoomPathHelpers.cpp.o
            vizdoom::initializeThisSharedObjectPath() in ViZDoomPathHelpers.cpp.o
        boost::filesystem::detail::path_algorithms::append_v3(boost::filesystem::path&, char const*, char const*), referenced from:
            vizdoom::relativePath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in ViZDoomPathHelpers.cpp.o
            vizdoom::relativePath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in ViZDoomPathHelpers.cpp.o
        boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*), referenced from:
            vizdoom::fileExists(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in ViZDoomPathHelpers.cpp.o
            vizdoom::fileExistsAndCanBeRead(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in ViZDoomPathHelpers.cpp.o
            vizdoom::checkFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in ViZDoomPathHelpers.cpp.o
            vizdoom::checkFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in ViZDoomPathHelpers.cpp.o
        boost::filesystem::detail::absolute(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*), referenced from:
            vizdoom::initializeThisSharedObjectPath() in ViZDoomPathHelpers.cpp.o
        boost::chrono::steady_clock::now(), referenced from:
            vizdoom::DoomController::DoomController() in ViZDoomController.cpp.o
            vizdoom::DoomController::generateInstanceId() in ViZDoomController.cpp.o
        boost::detail::thread_data_base::~thread_data_base(), referenced from:
            boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf0<void, vizdoom::DoomController>, boost::_bi::list1<boost::_bi::value<vizdoom::DoomController*>>>>::~thread_data() in ViZDoomController.cpp.o
            boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf0<void, vizdoom::DoomController>, boost::_bi::list1<boost::_bi::value<vizdoom::DoomController*>>>>::~thread_data() in ViZDoomController.cpp.o
        boost::thread::join_noexcept(), referenced from:
            vizdoom::DoomController::close() in ViZDoomController.cpp.o
            vizdoom::DoomController::close() in ViZDoomController.cpp.o
        boost::thread::native_handle(), referenced from:
            vizdoom::DoomController::close() in ViZDoomController.cpp.o
            vizdoom::DoomController::close() in ViZDoomController.cpp.o
        boost::thread::start_thread_noexcept(), referenced from:
            boost::thread::thread<boost::_bi::bind_t<void, boost::_mfi::mf0<void, vizdoom::DoomController>, boost::_bi::list1<boost::_bi::value<vizdoom::DoomController*>>>>(boost::_bi::bind_t<void, boost::_mfi::mf0<void, vizdoom::DoomController>, boost::_bi::list1<boost::_bi::value<vizdoom::DoomController*>>>&&) in ViZDoomController.cpp.o
        boost::thread::detach(), referenced from:
            vizdoom::DoomController::close() in ViZDoomController.cpp.o
            vizdoom::DoomController::close() in ViZDoomController.cpp.o
        boost::thread::interrupt(), referenced from:
            vizdoom::DoomController::close() in ViZDoomController.cpp.o
            vizdoom::DoomController::close() in ViZDoomController.cpp.o
        boost::filesystem::path::end() const, referenced from:
            vizdoom::relativePath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in ViZDoomPathHelpers.cpp.o
        boost::filesystem::path::begin() const, referenced from:
            vizdoom::relativePath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in ViZDoomPathHelpers.cpp.o
        boost::thread::joinable() const, referenced from:
            vizdoom::DoomController::close() in ViZDoomController.cpp.o
            vizdoom::DoomController::close() in ViZDoomController.cpp.o
        typeinfo for boost::detail::thread_data_base, referenced from:
            typeinfo for boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf0<void, vizdoom::DoomController>, boost::_bi::list1<boost::_bi::value<vizdoom::DoomController*>>>> in ViZDoomController.cpp.o
        vtable for boost::detail::thread_data_base, referenced from:
            boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf0<void, vizdoom::DoomController>, boost::_bi::list1<boost::_bi::value<vizdoom::DoomController*>>>>::thread_data(boost::_bi::bind_t<void, boost::_mfi::mf0<void, vizdoom::DoomController>, boost::_bi::list1<boost::_bi::value<vizdoom::DoomController*>>>&&) in ViZDoomController.cpp.o
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      make[2]: *** [bin/libvizdoom.dylib] Error 1
      make[1]: *** [CMakeFiles/libvizdoom_shared.dir/all] Error 2
      make[1]: *** Waiting for unfinished jobs....
      [ 19%] Built target libvizdoom_static
      [ 19%] Linking C static library libdumb.a
      [ 34%] Built target dumb
      make: *** [all] Error 2
      
      Installation failed, you may be missing some dependencies.
      Please check https://github.com/mwydmuch/ViZDoom/blob/master/doc/Installation.md for details
      
      Traceback (most recent call last):
        File "/Users/thaddeuskopczynski/PersonalProgramming/PersonalPython/doom/doom/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Users/thaddeuskopczynski/PersonalProgramming/PersonalPython/doom/doom/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/thaddeuskopczynski/PersonalProgramming/PersonalPython/doom/doom/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/s1/jv2r2b257jz7kb04glknvbym0000gn/T/pip-build-env-pqs6eedp/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 404, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/s1/jv2r2b257jz7kb04glknvbym0000gn/T/pip-build-env-pqs6eedp/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 389, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/s1/jv2r2b257jz7kb04glknvbym0000gn/T/pip-build-env-pqs6eedp/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/s1/jv2r2b257jz7kb04glknvbym0000gn/T/pip-build-env-pqs6eedp/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 194, in <module>
        File "/private/var/folders/s1/jv2r2b257jz7kb04glknvbym0000gn/T/pip-build-env-pqs6eedp/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/s1/jv2r2b257jz7kb04glknvbym0000gn/T/pip-build-env-pqs6eedp/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/s1/jv2r2b257jz7kb04glknvbym0000gn/T/pip-build-env-pqs6eedp/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/s1/jv2r2b257jz7kb04glknvbym0000gn/T/pip-build-env-pqs6eedp/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/s1/jv2r2b257jz7kb04glknvbym0000gn/T/pip-build-env-pqs6eedp/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/s1/jv2r2b257jz7kb04glknvbym0000gn/T/pip-build-env-pqs6eedp/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/s1/jv2r2b257jz7kb04glknvbym0000gn/T/pip-build-env-pqs6eedp/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/private/var/folders/s1/jv2r2b257jz7kb04glknvbym0000gn/T/pip-build-env-pqs6eedp/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/s1/jv2r2b257jz7kb04glknvbym0000gn/T/pip-build-env-pqs6eedp/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/s1/jv2r2b257jz7kb04glknvbym0000gn/T/pip-build-env-pqs6eedp/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 182, in run
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['make', '-j', '7']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vizdoom
Failed to build vizdoom
ERROR: Could not build wheels for vizdoom, which is required to install pyproject.toml-based projects

[notice] A new release of pip available: 22.3.1 -> 23.3.1

There's nothing at the dependency install link. Thanks in advance for any help.

**Comment by DiggetyDoo** [comment]
Quick update: for some reason I've found that I can pip install it with no issues outside of pycharm in a mac terminal. I'm pretty confused why I can't install it in my venv

**Comment by mwydmuch** [comment]
Hi @DiggetyDoo, thanks for reporting the issue. It looks like during the first installation, the boost libraries for Intel Mac (x86_64) were found in your system instead of M1 (arm64) version. Have you purposely installed them via brew for some other project? Since you've managed to install it properly from the console, I assume that you had both versions installed, and PyCharm is somehow messing with your environment variables, making CMake to select another version. I would need to know what PyCharm is doing to set up Venv to try to replicate. However, soon, we will also provide precompile wheels for M1/2 Macs, which will solve the problem, so it won't be a problem in the future.

**Comment by DiggetyDoo** [comment]
Is there anything else I should be doing besides brew uninstall boost and brew install boost to reinstall? I wasn't able to find an arm64 specific version online, and the boost site claims to support apple silicon and macos sonoma. I'm not sure how to tell if I have two versions installed.

**Comment by mwydmuch** [comment]
I'm not an expert in brew, but by default, M1/2 packages are installed in different locations. On my Intel Mac boost (compiled for x86_64) is installed under `/usr/local/Cellar/` as in the log you posted. On my M2 machine, brew installs the arm64 version of boost and other packages under `/opt/homebrew/Cellar/`. You can check where brew thinks you package is installed by running `brew info boost`. As far as I know, brew doesn't support an easy way of installing both versions of packages at the same time, so I'm a bit surprised by a setup that seems to be present on your machine.

**Comment by DiggetyDoo** [comment]
That was the issue, I reinstalled boost entirely and had to run sudo pip. Thanks so much for your help, I definitely wouldn't have been able to figure it out alone!

**Comment by mwydmuch** [comment]
Thank you for confirming that you managed to solve it!
