### ISSUE TITLE
state.screen_buffer is black/gray image

### ISSUE THREAD

**Issue by FFLLDDS** [Farama-Foundation/ViZDoom#589]
When running for example the script _ViZDoom/examples/python/buffers.py_ from the ViZDoom-repo all state.screen_buffer-images are monochrome black/gray images. 

I am running everything in Ubuntu 22.04.4 in a conda environment with vizdoom==1.2.4 version. I built ViZDoom from source as described in _https://vizdoom.farama.org/introduction/building/_ for Anaconda/Miniconda . Except for the buffers, everything works fine. I noticed that before the window opens that displays the game screen, another window, with just a black screen, opens and closes immediately. I did not find anything in the FAQs or Issues that could point me in the right direction. Thank you very much.

**Comment by mwydmuch** [comment]
Hi @FFLLDDS, thanks for reporting the problem! I have a few questions:
- Can you provide a screenshot of what you see when you run `buffers.py`? You should see 4 OpenCV windows, two of them are monochrome, while two of them should have colors.
- If that is not the case, can you check the screen buffer variable? What is its shape? Does it seem to contain 3 different color channels (shape should be (y, x, 3))?
- Does it behave the same when using the latest release 1.2.3? You can install it using pip (`pip install vizdoom`); no need to build it from the source; 1.2.4 is a work in progress.

**Comment by FFLLDDS** [comment]
Hello @mwydmuch, thank you very much! I tried running `buffers.py` in a new conda environment with vizdoom==1.2.3 (`pip install vizdoom`), but I got the same results (see the screenshot). The buffers are monochrome gray/black, with  changing intensity of the gray/black in the screen buffer while the script is running. 

![vizdoom_buffers_py](https://github.com/Farama-Foundation/ViZDoom/assets/89402449/2630551d-79bd-4490-92d2-ec605e20d149)

**Comment by mwydmuch** [comment]
Sorry for the long reply; I'm currently on vacation. Thank you for the screenshot. I didn't initially understand the issue; I thought that you get the proper monochrome image (just lacking colors), not just a single gray color. I have limited access to my hardware, but I checked and it seems that in versions 1.2.3 and master branch version, this example should work properly.

Can you check if these buffers contain real information - the values actually differ? If not, then this is probably a ViZDoom issue, but if they are not, then it is probably an OpenCV issue (which I suspect, what version of OpenCV are you using)? 

Have you tried running the `labels_buffer.py` example? It is similar but focuses only on the labels buffer.

Thanks!

**Comment by FFLLDDS** [comment]
Hey, thanks for taking the time on your vacation. The OpenCV version in my conda environment is `opencv-python 4.10.0.84`. I checked the buffers when running `buffers.py`, for each buffer all entries have the same value. For example, the screen buffer has a shape of (480, 640, 3), filled with the same value at all locations. 
When I run `labels_buffer.py` not all values in the screen buffer are the same anymore, which might be only due to the bounding boxes, which are visible now. 

![vizdoom_labels_buffer_py](https://github.com/Farama-Foundation/ViZDoom/assets/89402449/4fc678f5-cd2a-4545-be58-b682d86c7847)

**Comment by mwydmuch** [comment]
Thank you, @FFLLDDS, for further investigation! So, indeed, it looks like a bug. I'm certainly going to look into this. Unfortunately, I'm not able to at the moment, I need to come back from vacation first (next Wednesday).

But I also need to know a little bit more about your environment. So I know you are running Ubuntu 22.04.4. Is it an ARM or x86_64 system? What is the conda version (both the python version and the specific release of conda) and the numpy version?

**Comment by FFLLDDS** [comment]
Hey @mwydmuch, thank you very much! The system is x86_64. My conda version is `conda 24.5.0`, and the python version of my current conda environment is `Python 3.9.19` with `numpy 2.0.0`. This is the environment, where I installed ViZDoom with `pip install vizdoom`. The environment where I installed ViZDoom from source had `Python 3.10.14`  and also `numpy 2.0.0` installed.

**Comment by mkschleg** [comment]
Try w/ `numpy 1.x`. I ran into the same problem, and downgraded numpy and it seems to fix the issue.

**Comment by mwydmuch** [comment]
Thanks, @mkschleg, for your comment! Indeed, it seems that ViZDoom needs to be updated and rebuilt to support numpy 2.0. I will do it soon, but it may take more or less one more week. @FFLLDDS, so for the current version, the only solution to this issue is to downgrade numpy.

**Comment by FFLLDDS** [comment]
Thanks @mkschleg, @mwydmuch, it works with downgraded numpy.

**Comment by mwydmuch** [comment]
This is now fixed in the new release 1.2.4.

**Comment by 222464** [comment]
I believe this issue has returned, I tested with numpy 1.26.4 and it works, but beyond that (>=2) it only gives various shades of gray as output.

**Comment by 222464** [comment]
After some further investigation, it seems I can only install Vizdoom 1.2.2, which is why this issue appears. It seems the current Vizdoom does not yet support CPython 3.13, which for some reason causes it to install 1.2.2.

**Comment by mwydmuch** [comment]
Probably 1.2.2 was the last release without strict requirements on a range of supported Python versions. Unfortunately, we cannot fix it now. But I will test and hopefully release the Python 3.13 version of ViZDoom this week.

**Comment by 222464** [comment]
I have fixed it locally for now by just additionally appending 3.13 to the python versions.
